Enable strict compiler warnings (Linux) (#84)
Enable -pedantic some other strict compiler warnings. Some of the more
significant changes required to support these flags are:

* Macros used by //fly/logger apparently relied on a GNU extension, e.g.:

      #define LOGD(format, ...) _LOG(Debug, Format(format, ##__VA_ARGS__))

  Results in:

      error: token pasting of ',' and __VA_ARGS__ is a GNU extension

  The standard compliant implementation is unfortunately quite macro-heavy,
  especially because MSVC apparently pre-processes __VA_ARGS__ badly. This
  results in some particularly verbose macros for counting variadic arguments
  and grabbing either just-the-first or all-but-the-first argument.
  These macros are hidden in //fly/logger/detail/logger_macros.h.

* Let files.mk-specific flags (e.g. $(CLFAGS_$(d))) override default flags
  (e.g. $(CFLAGS)). Mainly, googletest needs to be compiled with slightly
  less strict options.

* Float equality is now forbidden. The one use case was //fly/types/json.
  Instead, equality is determined via approximation (using the machine
  epsilon as a threshold).

* The following C-style practices are now forbidden: C-style casts, using
  zero as nullptr (i.e. NULL), implicit signedness conversions.

Useful links for reference:

    https://clang.llvm.org/docs/DiagnosticsReference.html
    https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
    https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html